### ISSUE TITLE
Remaining functions to implement

### ISSUE THREAD

**Issue by Lucas-Mc** [MIT-LCP/wfdb-python#222]
A to-do list of the remaining functions from the [original C code](https://www.physionet.org/physiotools/wag/wag.htm) still left to implement:

- [x] a2m: converting between AHA and WFDB formats
- [x] ad2m: converting between AHA DB and WFDB formats
- [x] ahaconvert: converting between AHA DB and WFDB formats
- [x] ahaecg2mit: converting between AHA .ecg and .txt files and WFDB formats
- [x] m2a: converting between WFDB and AHA formats
- [x] md2a: converting between WFDB and AHA DB formats
- [x] ann2rr: convert annotation files to interval lists
- [x] rr2ann: convert interval lists to annotation files 
- [ ] bxb: ANSI/AAMI-standard beat-by-beat annotation comparator
- [ ] calsig: calibrate signals of a WFDB record
- [x] ~~coherence: estimate coherence and cross-spectrum of two time series~~
- [x] ~~dfa: detrended fluctuation analysis~~
- [x] ~~ecgeval: generate and run ECG analyzer evaluation script~~
- [x] ~~ecgpuwave: QRS detector and waveform limit locator #75 #134 #136~~
- [x] edf2mit: convert between EDF and WFDB-compatible formats
- [x] mit2edf: convert between WFDB-compatible and EDF formats
- [x] rdedfann: extract annotations from an EDF+ file
- [x] ~~edr: derive a respiration signal from an ECG~~
- [ ] epicmp: ANSI/AAMI-standard episode-by-episode annotation comparator
- [x] ~~fft: fast Fourier transform~~
- [x] ~~fir: general-purpose FIR filter for WFDB records~~
- [x] ~~gqfuse: combine QRS annotation files~~
- [x] gqrs: QRS detector
- [x] gqpost: QRS post-processor
- [x] ~~hrfft: calculate the heart rate FFT~~
- [x] ~~hrlomb: calculate the heart rate Lomb periodogram~~
- [x] ~~hrmem: calculate and plot heart rate power spectra~~
- [x] ~~hrstats: collect and summarize heart rate statistics from an annotation file~~
- [x] ~~ihr: calculate instantaneous heart rate~~
- [x] ~~imageplt: plot a greyscale image~~
- [x] ~~log10: calculate common logarithms of two-column data~~
- [x] ~~lomb: estimate power spectrum using the Lomb periodogram method~~
- [x] ~~lwcat: postprocess output of plt to make PostScript, EPS, PDF or PNG~~
- [x] ~~memse: estimate power spectrum using maximum entropy (all poles) method~~
- [x] ~~mfilt: general-purpose median filter for WFDB records~~
- [ ] mrgann: merge annotation files
- [ ] mxm: ANSI/AAMI-standard measurement-by-measurement annotation comparator #245 
- [x] ~~nguess: guess the times of missing normal beats in an annotation file~~
- [x] ~~nst: noise stress test for ECG analysis programs~~
- [ ] parsescp: parse SCP-ECG, optionally save in PhysioBank-compatible format
- [x] ~~plot2d: make 2-D plots from text files of data, using gnuplot~~
- [x] ~~plot3d: make 3-D plots from text files of data, using gnuplot~~
- [x] ~~plotstm: produce scatter plot of ST measurement errors on a PostScript device~~
- [x] ~~plt: make 2-D plots~~
- [x] ~~pltf: make function plots~~
- [x] ~~pnnlist: derive pNNx statistics from an annotation interval list~~
- [x] ~~pNNx: derive pNNx statistics from annotation file~~
- [x] pnwlogin: provide direct access to PhysioNetWorks for WFDB applications
- [x] pschart: produce annotated 'chart recordings' on a PostScript device
- [x] psfd: produce annotated 'full-disclosure' plots on a PostScript device
- [x] rdann: read a WFDB annotation file
- [x] rdsamp: read WFDB signal files
- [ ] rxr: ANSI/AAMI-standard run-by-run annotation comparator
- [x] sampfreq: show sampling frequency for a record
- [x] setwfdb: set WFDB environment variables
- [x] cshsetwfdb: set WFDB environment variables for C-shell
- [ ] sigamp: measure signal amplitudes of a WFDB record
- [ ] sigavg: calculate averages of annotated waveforms
- [x] signame: print names of signals of a WFDB record
- [ ] signum: print signal numbers of a WFDB record having specified names
- [ ] skewedit: edit skew fields of header file(s)
- [ ] snip: copy an excerpt of a WFDB record
- [ ] sortann: rearrange annotations in canonical order
- [x] sqrs: single-channel QRS detector
- [x] ~~sqrs125: single-channel QRS detector designed for 125 Hz input~~
- [x] ~~stepdet: single-channel step change detector~~
- [x] sumann: summarize the contents of a WFDB annotation file
- [ ] sumstats: derive aggregate statistics from bxb, rxr, etc., line-format output
- [x] ~~tach: heart rate tachometer~~
- [x] time2sec: convert WFDB standard time format into seconds
- [x] ~~wabp: arterial blood pressure (ABP) pulse detector~~
- [x] wav2mit: convert between .wav and WFDB-compatible formats
- [x] mit2wav: convert between WFDB-compatible and .wav formats
- [x] wave: waveform analyzer, viewer, and editor
- [x] wfdb-config: print WFDB library version and configuration info
- [x] wfdb2mat: convert WFDB-compatible signal file to Matlab .mat file
- [ ] wfdbcat: copy WFDB files to standard output
- [ ] wfdbcollate: collate WFDB records into a multi-segment record
- [x] wfdbdesc: read signal specifications
- [x] wfdbmap: make a synoptic map of a WFDB record #222 
- [x] wfdbtime: convert time to sample number, elapsed, and absolute time
- [x] wfdbwhich: find a WFDB file and print its pathname
- [x] ~~wqrs: single-channel QRS detector based on length transform #173 ~~
- [x] wrann: write a WFDB annotation file
- [x] wrsamp: write WFDB signal files
- [ ] xform: sampling frequency, amplitude, and format conversion for WFDB records

**Comment by alistairewj** [comment]
Quite a list! I'm not sure they are all worth implementing though; especially as there are other tools in the Python ecosystem. My thoughts are that wfdb-python should focus on the I/O between WFDB compatible records and Python. Looking at the list:

* plotting seems out of scope -  `plot2d`, `plot3d`, `plotstm`, `plt`, `pltf`, `imageplt`, `lwcat`, `pschart`, `psfd` can all be done by existing tools once the data is in Python (or aren't relevant if using Python)
* `coherence`, `dfa`, `nguess`, `sqrs125`, `tach`,  `ecgpuwave`, `ecgeval`, `wave`, `wabp` - all various types of ECG signal processing, which again seems like it could be separate from this package
* `fft`, `fir`, `lomb`, `mfilt`, `memse` - scipy signal processing functions which I know already exist

**Comment by AbdulAlkurdi** [comment]
I am interested in the ` wfdbmap` function.

**Comment by Lucas-Mc** [comment]
Hey @AbdulAlkurdi, thanks for the suggestion! [Here](https://www.physionet.org/physiotools/wag/wfdbma-1.htm) is where you can find the documentation and source code if you want a go at it! 👍

**Comment by Lucas-Mc** [comment]
I agree @alistairewj, too many which can be easily in Python instead of C or from external packages after the conversion! I'll add check marks to the ones you stated though I think `ecgpuwave` has gain some interest here #75 #134 #136. Any thoughts?

**Comment by alistairewj** [comment]
Hmm, feels like it would be better served by a dedicated package to ECG analysis, e.g. something like [ecg-kit](https://physionet.org/content/ecgkit/1.0/) (MATLAB) but in Python.

The closest one I know of is [BioSPPy](https://biosppy.readthedocs.io/en/stable/) - have only briefly used it myself but seems to fulfill the role!

We do have an energy based QRS detector (mostly because @cx1111 was interested in implementing one), so we could consider adding a wavelet based QRS detector. I'd say it's not at all a necessity, just a fun side project, so it's really only worth it if it interests you.

**Comment by JanCBrammer** [comment]
@Lucas-Mc, @alistairewj, there are a number of packages dedicated to biosignal processing (including ECG and PPG). [Neurokit](https://github.com/neuropsychology/NeuroKit) presents a [comprehensive overview](https://neurokit2.readthedocs.io/en/latest/tutorials/software.html). Maybe pointing users to those packages would be an option to prevent feature creep in `wfdb` (i.e., adding non-IO related features)?

**Comment by Lucas-Mc** [comment]
Hey @JanCBrammer, it looks like you are a developer for `Neurokit`.. do you have any functions off the top of your head that would cover any of these before I look at the overview?

**Comment by JanCBrammer** [comment]
@Lucas-Mc, the [overview](https://neurokit2.readthedocs.io/en/latest/tutorials/software.html) I was referring to is an attempt to gather all packages in the Python and Matlab ecosystem that deal with biosignal processing. I don't know from the top of my head where in those packages to locate the signal processing functions that you listed above. But I'm sure that collectively the packages cover a lot of ground :)

**Comment by alistairewj** [comment]
Yeah I agree something like `ecgpuwave` is useful but it feels out of scope as mentioned by @JanCBrammer. So probably what makes the most sense is the following:

* we can leave xqrs since it is there
* avoid adding new signal processing functionality; let's leave that to other packages
* create and link to a new repository for tracking useful physiologic signal processing tools, we can model this after one of the [awesome repositories](https://github.com/vinta/awesome-python)

Given this, looking back at your list, I'd check off the following as being out of scope:  `ecgpuwave`, `edr`, `gqfuse`, `hrfft`, `hrlomb`, `hrmem`, `hrstats`, `ihr`, `log10`, `nst`, `pnnlist`, `pNNx`, `stepdet`, `wqrs`

**Comment by Lucas-Mc** [comment]
Awesome, thanks @alistairewj, this brings us down to 40 functions! I didn't know about `awesome repositories` and that's going to save a lot of time when trying to find packages to link to! Also, thanks @JanCBrammer for your suggestions as well! 👍

**Comment by Lucas-Mc** [comment]
I think it's also safe to say that AHA format isn't really used anymore so I'll remove all of those!

**Comment by fabbra** [comment]
Is there a timeline / expected date when the `bxb` function will be implemented in Python? 
Is there any work already ongoing?

**Comment by bemoody** [comment]
> Is there a timeline / expected date when the `bxb` function will be
> implemented in Python? Is there any work already ongoing?

Good question!  Please create a separate issue so we can discuss the
specifics of how that function ought to work.

**Comment by cx1111** [comment]
Going to close this. We can use individual issues for high-yield functions to be ported over.
