### ISSUE TITLE
Todo list for signal processing

### ISSUE THREAD

**Issue by Dubrzr** [MIT-LCP/wfdb-python#56]
On branch sigproc

Signal processing:
- [x] Normalization (resize a signal between a lower and upper bound)
- [x] Resampling (signal and annotation position)

Detectors:
- Basic
  - [x] Simple peak detection (/\ or \\/ or /-\*\ or \\-\*/)
- QRS:
  - [x] gqrs integration

Misc:
  - [x] Peak corrector (nearest best peak)
